version: "3.7"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  rpcproxy:
    image: lumeweb/rpcproxy:latest
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 80
    depends_on:
      - handshake
    networks:
      shared:
        ipv4_address: 10.10.10.122
  nginx:
    depends_on:
      - rpcproxy
