version: "3.7"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  gundns:
    image: lumeweb/gundns:master
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RPC_PROXY_HOST="rpcproxy"
      - RPC_PROXY_PORT="80"
    volumes:
      - ./docker/data/gundns/data:/app/data
    expose:
      - 8081
    networks:
      shared:
        ipv4_address: 10.10.10.124
  nginx:
    depends_on:
      - rpcproxy
